services:
  postgres:
    image: postgres:14.5
    container_name: meet-ease-database
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    tmpfs:
      - /var/lib/postgresql
volumes:
  postgres:
    driver: local
